# ==========================================
# APPLICATION
# ==========================================

spring.application.name=secure-medical-data


# ==========================================
# DATABASE - MYSQL
# ==========================================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# ==========================================
# SERVER
# ==========================================

server.port=8080

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

encryption.secret=${ENCRYPTION_SECRET}